import os
import base64
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import (
    Mail, Attachment, FileContent, FileName,
    FileType, Disposition
)
from dotenv import load_dotenv

load_dotenv()

SENDGRID_API_KEY  = os.getenv("SENDGRID_API_KEY")
SENDGRID_FROM     = os.getenv("SENDGRID_FROM_EMAIL")


def send_report_email(
    to_email:    str,
    user_name:   str,
    disease:     str,
    risk_level:  str,
    probability: float,
    pdf_bytes:   bytes,
) -> bool:
    """
    Sends a PDF health report to the user via email.
    Returns True if sent successfully, False otherwise.
    """
    pct        = round(probability * 100)
    risk_emoji = "🔴" if risk_level == "HIGH" else "🟡" if risk_level == "MEDIUM" else "🟢"

    subject = f"Your HealthAI Report — {disease.title()} Risk Assessment"

    html_content = f"""
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">

      <div style="background: #1a1f3a; padding: 30px; border-radius: 12px 12px 0 0;">
        <h1 style="color: #ffffff; margin: 0; font-size: 24px;">HealthAI</h1>
        <p style="color: #a5b4fc; margin: 4px 0 0;">Patient Risk Assessment Report</p>
      </div>

      <div style="background: #ffffff; padding: 30px; border: 1px solid #e5e7eb;">
        <p style="font-size: 16px; color: #1a1f3a;">Dear <strong>{user_name}</strong>,</p>
        <p style="color: #6b7280;">
          Your health risk assessment report is ready. Here's a quick summary:
        </p>

        <div style="background: #f9fafb; border-radius: 10px; padding: 20px; margin: 20px 0;">
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; color: #6b7280; font-size: 14px;">Disease Assessed</td>
              <td style="padding: 8px 0; font-weight: bold; color: #1a1f3a; font-size: 14px;">
                {disease.title()}
              </td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #6b7280; font-size: 14px;">Risk Level</td>
              <td style="padding: 8px 0; font-weight: bold; font-size: 14px;
                color: {'#dc2626' if risk_level == 'HIGH' else '#d97706' if risk_level == 'MEDIUM' else '#059669'}">
                {risk_emoji} {risk_level}
              </td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #6b7280; font-size: 14px;">Probability</td>
              <td style="padding: 8px 0; font-weight: bold; color: #1a1f3a; font-size: 14px;">
                {pct}%
              </td>
            </tr>
          </table>
        </div>

        <p style="color: #6b7280; font-size: 14px;">
          Your full report with detailed risk factors, AI explanations, and personalized
          health recommendations is attached as a PDF.
        </p>

        <div style="background: #fef3c7; border-left: 4px solid #f59e0b;
                    padding: 12px 16px; border-radius: 4px; margin: 20px 0;">
          <p style="color: #92400e; font-size: 13px; margin: 0;">
            <strong>Disclaimer:</strong> This report is for informational purposes only
            and is not a substitute for professional medical advice. Please consult a
            qualified healthcare provider.
          </p>
        </div>
      </div>

      <div style="background: #f9fafb; padding: 20px;
                  border-radius: 0 0 12px 12px; text-align: center;
                  border: 1px solid #e5e7eb; border-top: none;">
        <p style="color: #9ca3af; font-size: 12px; margin: 0;">
          Generated by HealthAI Prediction System
        </p>
      </div>

    </div>
    """

    # Attach PDF
    encoded_pdf = base64.b64encode(pdf_bytes).decode()
    attachment  = Attachment(
        FileContent(encoded_pdf),
        FileName(f"healthai_{disease}_report.pdf"),
        FileType("application/pdf"),
        Disposition("attachment")
    )

    message = Mail(
        from_email=SENDGRID_FROM,
        to_emails=to_email,
        subject=subject,
        html_content=html_content
    )
    message.attachment = attachment

    try:
        sg  = SendGridAPIClient(SENDGRID_API_KEY)
        res = sg.send(message)
        print(f"Email sent to {to_email} — status: {res.status_code}")
        return res.status_code in [200, 201, 202]
    except Exception as e:
        print(f"Email error: {e}")
        return False